dist: xenial
language: cpp
compiler:
- gcc
- clang
python: 3.7
addons:
  apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - python3
        - python3-pip
        - python3-setuptools
install:
- pip3 install --user --upgrade pip
- pip3 install --user conan
- conan user
- wget https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Linux-x86_64.tar.gz
- tar -xvzf cmake-3.13.4-Linux-x86_64.tar.gz
- export CONAN_CMAKE_PROGRAM=$(pwd)/cmake-3.13.4-Linux-x86_64/bin/cmake
- ${CONAN_CMAKE_PROGRAM} --version
script:
- conan create base foo/bar
- conan create dependent foo/bar
